apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-gpu-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.ngc.nvidia.com/nvidia
    targetRevision: v24.6.0  # Use the latest version available
    chart: gpu-operator
    helm:
      values: |
        driver:
          enabled: true
          startupProbe: 60s
        mig:
          strategy: single
        nfd:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: gpu-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true